Remote networks datasource
Twingate/terraform-provider-twingate pull request #114
Opened 2022-06-13 20:27 UTC by vmanilo

Resolves https://github.com/Twingate/terraform-provider-twingate/issues/103

Based on PR: https://github.com/Twingate/terraform-provider-twingate/pull/112

## Changes
- added datasource for remote-networks

2022-06-13 21:00 UTC, vmanilo commented on twingate/datasource_remote_networks.go
> +		Description: "A Remote Network represents a single private network in Twingate that can have one or more Connectors and Resources assigned to it. You must create a Remote Network before creating Re
@alexmensch please check text

2022-06-13 21:01 UTC, vmanilo commented on twingate/datasource_remote_networks.go
> +				Description: "The name of the Remote Network",
@alexmensch please check text

2022-06-13 21:01 UTC, vmanilo commented on twingate/datasource_remote_networks.go
> +							Description: "The ID of the Remote Network",
@alexmensch please check text

2022-06-13 21:01 UTC, vmanilo commented on twingate/datasource_remote_networks.go
> +							Description: "The name of the Remote Network",
@alexmensch please check text

2022-06-13 21:47 UTC, alexmensch approved these changes
Made a small addition to the text, otherwise all other text looks good to me.

2022-06-13 22:13 UTC, ekampf reviewed
One thing I'm missing is where in the docs does it explain what the data sources return?
The description for `remoote_network` and `remote_networks` is identical but one returns a single instance and one returns a list of matches...

2022-06-13 22:18 UTC, ekampf commented
Never mind figured it out

2022-06-13 22:24 UTC, ekampf commented on twingate/client_resource.go
> +	ErrTooManyGroupsError              = errors.New("provider does not support more than 50 groups per resource")
It doesn't seem like `client_resource` is the right place for these to be as these are generic to all clients...

2022-06-13 22:27 UTC, ekampf commented on twingate/client_resource.go
> +	ErrTooManyGroupsError              = errors.New("provider does not support more than 50 groups per resource")
Feel free to fix on a separate PR

2022-06-13 22:27 UTC, ekampf approved these changes
Approving but we need a followup PR to move clients t errors from client_resource.go to a better place

2022-06-13 23:03 UTC, ekampf requested changes
We're considering making Remote Network name unique which would mean we wouldn't need this data source and could query by either id or name in the non-plural one.

So lets put this PR on hold for now

2022-06-28 19:25 UTC, alexmensch commented on docs/data-sources/remote_network.md
> +  id = "<your network's id>"
We should change this to the following to make it more explicit:

`id = "<remote network id>"`

And then we should clarify where this ID comes from, which I'll add in a separate comment.

2022-06-28 19:30 UTC, alexmensch commented on docs/data-sources/remote_networks.md
> +  name = "<your network's name>"
Change to:

`name = "<remote network name>"`

2022-06-28 19:38 UTC, alexmensch requested changes

2022-06-28 19:38 UTC, alexmensch commented on docs/data-sources/remote_network.md
> +
Let's add a clarification below this on why we have a plural data source:

`Remote Network names are not constrained to be unique within Twingate, so it is possible that this data source will return multiple list items.`

2022-08-16 19:08 UTC, ekampf commented
Closing as we now support name uniqueness and this is unecessary

2022-08-16 19:08 UTC, closed without merging