Fix docs for nested objects in plural datasources
Twingate/terraform-provider-twingate pull request #157
Opened 2022-07-24 18:50 UTC by vmanilo

Resolves `<github issue>`

## Changes
- Fix docs for connectors datasource

2022-08-02 02:12 UTC, ekampf approved these changes

2022-08-02 02:43 UTC, ekampf approved these changes

2022-08-02 02:46 UTC, ekampf commented
@vmanilo I'm not sure whats the purpose of this PR. It links to an issue titled "Add ability to specify descriptions for nested schema attributes" but describes the PR as "Fix docs for connectors datasource" and then the code edits not just connectors.

2022-08-02 02:47 UTC, ekampf requested changes
Needs more details on description\issue

2022-08-02 06:19 UTC, vmanilo commented
> Needs more details on description\issue

sure, updated description

as you see in changes nested objects in the schema now has descriptions, the issue is about that description was empty

```
- `id` (String)
- `name` (String)
- `remote_network_id` (String)

+ `id` (String) The ID of the Connector
+ `name` (String) The Name of the Connector
+ `remote_network_id` (String) The ID of the Remote Network attached to the Connector
```

2022-08-02 19:03 UTC, ekampf approved these changes

2022-08-03 01:36 UTC, ekampf approved these changes

2022-08-13 19:03 UTC, merged