New resource properties
Twingate/terraform-provider-twingate pull request #253
Opened 2023-01-15 18:17 UTC by vmanilo

Resolves https://github.com/Twingate/terraform-provider-twingate/issues/251

## Changes
- added optional resource properties: is_visible and is_browser_shortcut_enabled

2023-01-15 18:18 UTC, vmanilo commented on twingate/internal/provider/resource/resource.go
> +				Description: "Indicates if the Resource is active.",
@alexb-twingate please check doc string

2023-01-15 18:19 UTC, vmanilo commented on twingate/internal/provider/resource/resource.go
> +				Description: "Indicates whether this Resource will display a browser shortcut in the client.",
@alexmensch please check doc string

2023-01-17 17:54 UTC, ekampf approved these changes

2023-01-17 17:57 UTC, ekampf approved these changes
Code looks good. Description for `is_visible` is wrong I'll wait for @alexmensch  to give a fix before merging

2023-01-17 18:21 UTC, alexmensch requested changes

2023-01-17 18:21 UTC, alexmensch commented on docs/resources/resource.md
> +- `is_browser_shortcut_enabled` (Boolean) Indicates whether this Resource will display a browser shortcut in the client.
Description here should be: `Controls whether an "Open in Browser" shortcut will be shown for this Resource in the Twingate Client.`

2023-01-17 18:21 UTC, alexmensch commented on docs/resources/resource.md
> +- `is_visible` (Boolean) Indicates if the Resource is active.
Description here: `Controls whether this Resource will be visible in the main Resource list in the Twingate Client.`

2023-01-17 19:52 UTC, alexmensch approved these changes

2023-01-17 19:55 UTC, merged