Add `twingate_group` resource
Twingate/terraform-provider-twingate pull request #56
Opened 2022-03-21 19:12 UTC by sapslaj

- JIRA Ticket URL: 🙂 i would if i could

## Changes

- Adds `twingate_group` resource.
- Currently can only manage group name

2022-03-22 21:46 UTC, ekampf commented
@sapslaj thanks a lot for contributing!
We're actually in the process of setting ups the infrastructure to support outside contributions - run CI on forked repos, do not require a JIRA ticket.

I have configured CircleCI to run on PRs from forks but I have no way to trigger it for your repo - can you push a change so that it triggers?

2022-03-23 17:57 UTC, ekampf commented
@sapslaj awesome!  we'll review and merge ASAP

2022-03-25 23:06 UTC, ekampf requested changes
@sapslaj thanks a lot for the PR! We just need a few minor fixes to be able to merge...

2022-04-04 15:05 UTC, romankor commented
@sapslaj ping ...

2022-04-07 00:07 UTC, sapslaj commented
Hey @romankor and all, haven't forgotten about this just haven't had the time to work on it yet.

2022-04-12 19:22 UTC, romankor commented
@sapslaj do you mind if we take over from here ? we have some bandwidth now and can work on the provider

2022-04-14 20:28 UTC, vmanilo commented
Added proposed changes in this PR https://github.com/Twingate/terraform-provider-twingate/pull/72

2022-04-18 00:19 UTC, romankor commented on docs/resources/group.md
> +### Read-Only
Lets add an example of how to use and import groups , like in all other resources 
in order for that to happen you need to add a corresponding file to 
<img width="552" alt="image" src="https://user-images.githubusercontent.com/2689706/163737596-612865c6-58b9-4928-b60c-940307388f63.png">

2022-04-28 20:29 UTC, romankor commented
@sapslaj closing this one , since it was already merge in another PR

2022-04-28 20:29 UTC, closed without merging