Add twingate_group resource - UPD
Twingate/terraform-provider-twingate pull request #72
Opened 2022-04-14 20:16 UTC by vmanilo

Original PR https://github.com/Twingate/terraform-provider-twingate/pull/56

2022-04-18 00:20 UTC, romankor requested changes
I went over all the comments from the previous PR and everything seems to be addressed 

here is another comment that made on the other PR 
https://github.com/Twingate/terraform-provider-twingate/pull/56/files#r851820228

and also a small on on that one

2022-04-18 08:27 UTC, vmanilo commented on twingate/client_group_test.go
> +		assert.EqualError(t, err, fmt.Sprintf(`failed to read group with id id: Post "%s": error_1`, client.GraphqlServerURL))
yes, updated groupIds in other tests as well

2022-04-18 08:28 UTC, vmanilo commented
added terraform example to create/import twingate_group

2022-04-28 17:28 UTC, romankor approved these changes
GTM

2022-04-28 20:26 UTC, merged